dist: trusty
language: node_js
node_js:
- "10"

install:
- npm install

script:
- export TAG_REGEX=^[0-9]+\.[0-9]+\.[0-9]+
- npm run lint
- npm run build
- npm run test
- if [[ $TRAVIS_TAG =~ $TAG_REGEX ]];
  then
    npm run doc;
    npm run example;
  fi

deploy:
- provider: npm
  skip_cleanup: true
  email: uxteam@adidas-group.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    condition: $TRAVIS_TAG =~ $TAG_REGEX
- provider: pages
  skip-cleanup: true
  local-dir: ./example
  github-token: $GITHUB_TOKEN
  on:
    tags: true
    condition: $TRAVIS_TAG =~ $TAG_REGEX
